FROM openjdk:16-jdk-alpine
ARG PORT=8080
ARG APPLICATION_VERSION="0.0.1-SNAPSHOT"
ARG SERVICE_NAME="logicalinventory-api"


ENV APPLICATION_VERSION ${APPLICATION_VERSION}

COPY build/libs/${SERVICE_NAME}-${APPLICATION_VERSION}.jar .
ENV SERVICE_PATH=/${SERVICE_NAME}-${APPLICATION_VERSION}.jar

EXPOSE ${PORT}
ENTRYPOINT ["sh","-c","java -jar ${SERVICE_PATH}"]
