version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: node-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout


      - run: 
          name: test env
          command: |
            echo BUILD_NUMMBER=012 > $BASH_ENV
            BUCKET_TO_DEPLOY=""
            case $CIRCLE_BRANCH in
                  develop)
                      BUCKET_TO_DEPLOY=${INT_BUCKET} > $BASH_ENV
                  ;;
                  epic)
                      BUCKET_TO_DEPLOY=${EPIC_BUCKET} > $BASH_ENV
                  ;;
                  qat)
                      BUCKET_TO_DEPLOY=${QAT_BUCKET} > $BASH_ENV
                  ;;
                  master)
                      BUCKET_TO_DEPLOY=${PROD_BUCKET} > $BASH_ENV
                  ;;
                  *)
                      echo "No redeployment URL defined for $CIRCLE_BRANCH; exiting with error"
                      exit 1
                  ;;
              esac

              echo $BUCKET_TO_DEPLOY > t.txt
              echo $BUCKET_TO_DEPLOY"Waara"
              if [ -n $BUCKET_TO_DEPLOY ];then
                echo "a gya"
              fi  


      - run: 
          name: test env echo
          command: |
            echo ${BUILD_NUMMBER}
            echo ${BUCKET_TO_DEPLOY}
